import React from 'react';
import './setup';
import { Dropdown, Icon, MethodBadge, MiniCheck, PulseLogo } from './components';
import { downloadFile } from './download';
import { isDefined } from './isDefined';
import './ExportData';
import { ImportModal } from './ImportData';
import { useI18n } from './useI18n';
import { useWorkspace } from './state/WorkspaceContext';
import { useRequest, type HistoryEntry } from './state/RequestContext';
import type { QaImportParsed, QaImportRequestMeta } from './import-parser';

// ── QA Touchstone — nav rail + collections sidebar ─────────────────────────
const { useState } = React;

function histDownload(name: string, content: string, mime: string) {
  // 統一走 download.ts：Tauri 用原生存檔對話框、其他環境 blob fallback。
  downloadFile(name, content, mime);
}
function histEntry(h: HistoryEntry) {
  const resp = window.QA.RESPONSES[h.id];
  const all = window.QA.COLLECTIONS.flatMap((c: any) => c.folders.flatMap((f: any) => f.requests));
  const meta = all.find((r: any) => r.id === h.id);
  return {
    name: meta ? meta.name : h.path,
    method: h.method,
    path: h.path,
    at: h.at,
    status: h.status,
    statusText: resp ? resp.statusText : '',
    timeMs: h.time,
    sizeBytes: resp ? resp.size : 0,
    responseHeaders: resp ? resp.headers : {},
    responseBody: resp ? resp.body : null,
  };
}
function histEsc(s: unknown) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
function histReportHtml(data: Array<ReturnType<typeof histEntry>>) {
  const sc = window.QATheme.statusColor;
  const rows = data
    .map(
      (d) =>
        `<tr><td>${histEsc(d.at)}</td><td class="m">${histEsc(d.method)}</td><td>${histEsc(d.path)}</td><td style="color:${sc(d.status)};font-weight:700">${histEsc(d.status)}</td><td>${histEsc(d.timeMs)}ms</td><td>${histEsc(d.sizeBytes)} B</td></tr>`
    )
    .join('');
  const bodies = data
    .map(
      (d) =>
        `<div class="call"><div class="ch"><span class="m">${histEsc(d.method)}</span> ${histEsc(d.path)} <b style="color:${sc(d.status)}">${histEsc(d.status)} ${histEsc(d.statusText)}</b></div>${d.responseBody != null ? `<pre>${window.highlightJson!(JSON.stringify(d.responseBody, null, 2))}</pre>` : '<div class="muted">no body</div>'}</div>`
    )
    .join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>QA Touchstone — API history (${data.length} calls)</title>
<style>
  body{margin:0;background:#15181c;color:#e6edf3;font-family:'Google Sans Code',ui-monospace,monospace;font-size:13px;padding:32px}
  .wrap{max-width:820px;margin:0 auto}h1{font-size:17px;margin:0 0 2px}.sub{color:#97a3ae;font-size:12px;margin-bottom:20px}
  table{width:100%;border-collapse:collapse;margin-bottom:24px}td{padding:7px 9px;border-bottom:1px solid #272d34;font-size:12px}.m{color:#4d9fff;font-weight:700}
  h2{font-size:12px;color:#97a3ae;text-transform:uppercase;letter-spacing:.05em;margin:0 0 12px}
  .call{border:1px solid #272d34;border-radius:8px;padding:12px;margin-bottom:10px}.ch{font-size:12px;margin-bottom:8px;word-break:break-all}.ch .m{margin-right:6px}
  pre{background:#1a1e23;border:1px solid #272d34;border-radius:8px;padding:12px;overflow:auto;font-size:12px;line-height:1.6;white-space:pre-wrap;word-break:break-word;margin:0}.muted{color:#626d77}
  .qa-j-key{color:#a9c7f2}.qa-j-str{color:#8fd6a6}.qa-j-num{color:#e6c07a}.qa-j-bool{color:#c2a6ef}.qa-j-null{color:#626d77;font-style:italic}
  .foot{color:#626d77;font-size:11px;margin-top:24px}
</style></head><body><div class="wrap">
  <h1>QA Touchstone · API call history</h1><div class="sub">${data.length} calls · exported ${new Date().toLocaleString()}</div>
  <table><tbody>${rows}</tbody></table>
  <h2>Responses</h2>${bodies}
  <div class="foot">Generated by QA Touchstone.</div>
</div></body></html>`;
}
function exportHistory(items: HistoryEntry[], fmt: string) {
  if (!items.length) return;
  const data = items.map(histEntry);
  const base = `qa-api-history-${items.length}calls-${new Date().toISOString().slice(0, 16).replace(/[:T]/g, '')}`;
  if (fmt === 'json') {
    histDownload(base + '.json', JSON.stringify(data, null, 2), 'application/json');
    return;
  }
  if (fmt === 'html') {
    histDownload(base + '.html', histReportHtml(data), 'text/html');
    return;
  }
  const lines = ['time,method,path,status,time_ms,size_bytes'];
  data.forEach((d) =>
    lines.push(`${d.at},${d.method},"${d.path}",${d.status},${d.timeMs},${d.sizeBytes}`)
  );
  histDownload(base + '.csv', lines.join('\n'), 'text/csv');
}

export interface NavRailProps {
  route: string;
  setRoute: (route: string) => void;
  busy?: boolean;
  flashAt?: number;
  active?: boolean;
}

function NavRail({ route, setRoute, busy, flashAt, active }: NavRailProps) {
  const { t } = useI18n();
  const items = [
    { key: 'home', icon: 'home', label: t('route.home') },
    { key: 'testgen', icon: 'sparkle', label: t('route.testgen') },
    { key: 'api', icon: 'send', label: t('route.api') },
    { key: 'realtime', icon: 'activity', label: t('route.realtime') },
    { key: 'runner', icon: 'play', label: t('route.runner') },
    { key: 'security', icon: 'shield', label: t('route.security') },
    { key: 'monitors', icon: 'clock', label: t('route.monitors') },
    { key: 'docs', icon: 'fileText', label: t('route.docs') },
    { key: 'perf', icon: 'gauge', label: t('route.perf') },
    { key: 'settings', icon: 'settings', label: t('route.settings') },
  ];
  return (
    <nav className="qa-rail">
      <div className="qa-rail-logo" title="QA Touchstone">
        <PulseLogo busy={busy} flashAt={flashAt} active={active} size={34} />
      </div>
      <div className="qa-rail-items">
        {items.map((it) => (
          <button
            key={it.key}
            className="qa-rail-btn"
            data-active={route === it.key ? '1' : '0'}
            onClick={() => setRoute(it.key)}
            title={it.label}
            aria-label={it.label}
          >
            <Icon name={it.icon} size={20} stroke={1.9} />
            <span className="qa-rail-tip">{it.label}</span>
          </button>
        ))}
      </div>
      <div className="qa-rail-foot">
        <div className="qa-rail-ver">{__APP_VERSION__.split('.').slice(0, 2).join('.')}</div>
      </div>
    </nav>
  );
}

export interface CollectionRowProps {
  req: QaImportRequestMeta;
  active: boolean;
  onClick: () => void;
}

function CollectionRow({ req, active, onClick }: CollectionRowProps) {
  return (
    <button className="qa-req" data-active={active ? '1' : '0'} onClick={onClick}>
      <MethodBadge method={req.method} size="sm" />
      <span className="qa-req-name">{req.name}</span>
    </button>
  );
}

export interface CollectionsPanelProps {
  onSelectHistory: (h: HistoryEntry) => void;
  onImport?: (payload: QaImportParsed & { format: string }) => void;
}

// Workspace / request 狀態改由 context 提供（8 個 props → 2 個）。
// onSelectHistory / onImport 仍為 prop：兩者都附帶路由切換（AppShell 職責）。
function CollectionsPanel({ onSelectHistory, onImport }: CollectionsPanelProps) {
  const { t } = useI18n();
  const { env, setEnv } = useWorkspace();
  const { req, selectRequest: onSelectRequest, history, dataVersion } = useRequest();
  const selectedReq = req.id;
  void dataVersion; // 讀取以在 collections 匯入後重新渲染清單
  const { COLLECTIONS, ENVIRONMENTS } = window.QA;
  // Default to the first collection open; everything else collapsed. Avoids
  // hard-coding seed IDs that may not exist after the workspace is reshaped.
  const [open, setOpen] = useState<Record<string, boolean>>(() =>
    COLLECTIONS[0] ? { [COLLECTIONS[0].id]: true } : {}
  );
  const [query, setQuery] = useState('');
  const [tab, setTab] = useState('collections');
  const [hSel, setHSel] = useState<number[]>([]);
  const [hMenu, setHMenu] = useState(false);
  const [importing, setImporting] = useState(false);
  const [exportMenu, setExportMenu] = useState(false);
  const toggleHSel = (i: number) =>
    setHSel((s) => (s.includes(i) ? s.filter((x) => x !== i) : [...s, i]));

  const toggle = (id: string) => setOpen((o) => ({ ...o, [id]: !o[id] }));
  const q = query.trim().toLowerCase();

  return (
    <aside className="qa-side">
      {/* Environment selector */}
      <div className="qa-side-env">
        <label className="qa-side-label">
          <Icon name="globe" size={12} /> {t('sidebar.environment')}
        </label>
        <Dropdown
          value={env.label}
          options={ENVIRONMENTS.map((e: any) => e.label)}
          onChange={(label: string) => setEnv(ENVIRONMENTS.find((x: any) => x.label === label))}
        />
        {env.baseUrl ? (
          <div className="qa-env-url">{env.baseUrl}</div>
        ) : (
          <div className="qa-env-url qa-env-url--empty">{t('sidebar.noBaseUrl')}</div>
        )}
      </div>

      {/* Tabs: collections / history */}
      <div className="qa-side-tabs">
        <button
          data-active={tab === 'collections' ? '1' : '0'}
          onClick={() => setTab('collections')}
        >
          <Icon name="layers" size={13} /> {t('sidebar.collections')}
        </button>
        <button data-active={tab === 'history' ? '1' : '0'} onClick={() => setTab('history')}>
          <Icon name="history" size={13} /> {t('sidebar.history')}
        </button>
      </div>

      {tab === 'collections' && (
        <>
          <div className="qa-side-tools">
            <div className="qa-search">
              <Icon name="search" size={13} />
              <input
                placeholder={t('sidebar.searchRequests')}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
              />
              {query && (
                <button onClick={() => setQuery('')} aria-label={t('common.clear')}>
                  <Icon name="x" size={12} />
                </button>
              )}
            </div>
            <button
              className="qa-side-import"
              title={t('sidebar.importTitle')}
              onClick={() => setImporting(true)}
            >
              <Icon name="download" size={14} /> {t('sidebar.import')}
            </button>
            <div className="qa-side-exportwrap">
              <button
                className="qa-side-import qa-side-iconbtn"
                title={t('sidebar.exportTitle')}
                aria-label={t('sidebar.exportTitle')}
                aria-expanded={exportMenu}
                onClick={() => setExportMenu((m) => !m)}
              >
                <Icon name="upload" size={14} />
              </button>
              {exportMenu && (
                <div className="qa-export-menu">
                  <div className="qa-export-menu-h">{t('sidebar.exportAsPostman')}</div>
                  {COLLECTIONS.map((c: any) => (
                    <button
                      key={c.id}
                      onClick={() => {
                        window.exportCollection!(c, env);
                        setExportMenu(false);
                      }}
                    >
                      <Icon name="folder" size={13} /> <span>{c.name}</span>
                      <span className="qa-col-count">{c.count}</span>
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
          <div className="qa-side-scroll">
            {COLLECTIONS.map((col: any) => {
              const reqs = col.folders
                .flatMap((f: any) => f.requests)
                .filter(
                  (r: any) =>
                    !q || r.name.toLowerCase().includes(q) || r.path.toLowerCase().includes(q)
                );
              if (q && reqs.length === 0) return null;
              const isOpen =
                (open[col.id] !== undefined ? open[col.id] : !!col.source) ||
                (q && reqs.length > 0);
              return (
                <div key={col.id} className="qa-col">
                  <button className="qa-col-head" onClick={() => toggle(col.id)}>
                    <Icon
                      name="chevron"
                      size={13}
                      className="qa-col-chev"
                      data-open={isOpen ? '1' : '0'}
                    />
                    <Icon name="folder" size={14} className="qa-col-folder" />
                    <span className="qa-col-name">{col.name}</span>
                    <span className="qa-col-count">{col.count}</span>
                  </button>
                  {isOpen && (
                    <div className="qa-col-body">
                      {reqs.map((r: any) => (
                        <CollectionRow
                          key={r.id}
                          req={r}
                          active={selectedReq === r.id}
                          onClick={() => onSelectRequest(r.id)}
                        />
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </>
      )}

      {tab === 'history' && (
        <div className="qa-side-scroll">
          {history.length === 0 && <div className="qa-empty-mini">{t('sidebar.noRequests')}</div>}
          {history.length > 0 && (
            <div className="qa-hist-bar">
              <span className="qa-meta">
                {hSel.length
                  ? t('sidebar.selected', { count: hSel.length })
                  : t('sidebar.calls', { count: history.length })}
              </span>
              <div className="qa-hist-export">
                <button
                  className="qa-hist-expbtn"
                  disabled={!hSel.length}
                  onClick={() => setHMenu((m) => !m)}
                >
                  <Icon name="download" size={12} /> {t('sidebar.export')}
                </button>
                {hMenu && hSel.length > 0 && (
                  <div className="qa-hist-menu">
                    {['html', 'json', 'csv'].map((f) => (
                      <button
                        key={f}
                        onClick={() => {
                          exportHistory(
                            hSel
                              .slice()
                              .sort((a, b) => a - b)
                              .map((i) => history[i])
                              .filter(isDefined),
                            f
                          );
                          setHMenu(false);
                        }}
                      >
                        {t('sidebar.report', { format: f.toUpperCase() })}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}
          {history.map((h, i) => (
            <div key={i} className="qa-hist-row">
              <MiniCheck on={hSel.includes(i)} onClick={() => toggleHSel(i)} />
              <button className="qa-hist" onClick={() => onSelectHistory(h)}>
                <MethodBadge method={h.method} size="sm" />
                <span className="qa-hist-path">{h.path}</span>
                <span className="qa-hist-meta">
                  <span style={{ color: window.QATheme.statusColor(h.status) }}>{h.status}</span>
                  <span className="qa-hist-time">{h.at}</span>
                </span>
              </button>
            </div>
          ))}
        </div>
      )}
      {importing && (
        <ImportModal
          onClose={() => setImporting(false)}
          onImport={(p) => {
            if (onImport) onImport(p);
            setImporting(false);
          }}
        />
      )}
    </aside>
  );
}

Object.assign(window, { NavRail, CollectionsPanel });

export { NavRail, CollectionsPanel };
