// 從 publicsuffix.org 抓取最新 Public Suffix List，解析成
// src/qa/psl.data.ts（自動產生、勿手改）。cookie jar 用它判斷
// 「哪些網域是公共後綴、不准設 Domain cookie」（supercookie 防禦）。
//
// 用法：node scripts/update-psl.mjs           （從網路抓最新版）
//       node scripts/update-psl.mjs <檔案路徑>（用本機已下載的 .dat）
//
// 規則格式（https://publicsuffix.org/list/）：
//   - `//` 開頭為註解、空行略過（ICANN 與 PRIVATE 兩節都收，瀏覽器同此行為）
//   - `*.foo` 萬用字元規則 → 存 base（foo）進 wildcards
//   - `!bar.foo` 例外規則 → 存（bar.foo）進 exceptions
//   - 其餘為一般規則
import fs from 'node:fs';

const SOURCE_URL = 'https://publicsuffix.org/list/public_suffix_list.dat';
const OUT = 'src/qa/psl.data.ts';

async function loadRaw() {
  const fileArg = process.argv[2];
  if (fileArg) return fs.readFileSync(fileArg, 'utf8');
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error(`fetch ${SOURCE_URL} -> HTTP ${res.status}`);
  return await res.text();
}

const raw = await loadRaw();
const rules = [];
const wildcards = [];
const exceptions = [];

for (const lineRaw of raw.split(/\r?\n/)) {
  const line = lineRaw.trim();
  if (!line || line.startsWith('//')) continue;
  // 規則行只取第一個空白前的 token（規格如此）
  const rule = line.split(/\s/)[0].toLowerCase();
  if (rule.startsWith('!')) exceptions.push(rule.slice(1));
  else if (rule.startsWith('*.')) wildcards.push(rule.slice(2));
  else rules.push(rule);
}

const today = new Date().toISOString().slice(0, 10);
const body = `// AUTO-GENERATED by scripts/update-psl.mjs — DO NOT EDIT BY HAND.
// Source: ${SOURCE_URL}
// Fetched: ${today} · rules=${rules.length} wildcards=${wildcards.length} exceptions=${exceptions.length}
// 更新方式：node scripts/update-psl.mjs（會覆寫本檔）

export const PSL_FETCHED = '${today}';
export const PSL_RULES: readonly string[] = ${JSON.stringify(rules)};
export const PSL_WILDCARDS: readonly string[] = ${JSON.stringify(wildcards)};
export const PSL_EXCEPTIONS: readonly string[] = ${JSON.stringify(exceptions)};
`;

fs.writeFileSync(OUT, body);
console.log(`wrote ${OUT}: ${rules.length} rules, ${wildcards.length} wildcards, ${exceptions.length} exceptions (${today})`);
